feat: added image and code block caption with example
satellytes/satellytes.com pull request #125
Opened 2021-08-18 15:08 UTC by WiebkeFr

pr contains:
- components for image and code block caption with changeable design
- example for both in a blog article

2021-08-31 14:18 UTC, georgiee requested changes
I see the feature being provide but not really used or demonstrated. I think we should double check if this change is ok.

2021-08-31 14:18 UTC, georgiee commented on blog-posts/howto-blog-post.md
> -cosnt myJavaScrip = true;
👍

2021-08-31 14:18 UTC, georgiee commented on blog-posts/howto-blog-post.md
> +```
this is different to the billing dashboard example where the text is just added as a paragraph?

2021-08-31 14:18 UTC, georgiee commented on blog-posts/github-billing-dashboard.md
>  ![screenshot of the Github billing dashboard with some charts](images/gh-billing-dashboard-screenshot-of-gh-dashboard.png)
I don't see an caption being added?

2021-08-31 14:18 UTC, georgiee commented on blog-posts/howto-blog-post.md
> +```
I don't see an example for this in the markdown being rendered which would make sense here, wouldn't it ?

2021-09-16 06:23 UTC, feedm3 commented
It looks like this PR is not working currently.

The idea here is that we provide captions for images and code blocks. I outlined it here https://github.com/satellytes/satellytes.com/issues/102

We can use Notion as guidance. They support this great feature really well.

2021-09-16 15:14 UTC, georgiee commented
Thanks for the feedback. The PR didn't make it clear what to expect and taking Notion as the guidance makes it much easier.

2021-11-23 10:37 UTC, georgiee commented
This is outdated and covered by these issues for the updated/aligned desing:

+ https://github.com/satellytes/satellytes.com/issues/179
+ https://github.com/satellytes/satellytes.com/issues/175

2021-11-23 10:37 UTC, closed without merging