chore: share panel color fix
satellytes/satellytes.com pull request #396
Opened 2022-02-11 10:17 UTC by milljoniaer

### This should fix the colors of the share and follow bar at the end of the blog posts:
- dark blue for the labels
- correct primary blue for the icons

### Browse the preview
https://satellytescommain21751-fixcolorblog.gtsb.io/blog/boosting-developer-productivity-with-github-actions/

![image](https://user-images.githubusercontent.com/78978542/153574227-9cb98d20-b233-4c17-90c3-04c1c88a4344.png)

#395

2022-02-11 12:07 UTC, georgiee requested changes
Thanks looks good! I would love to see the icons migrated to the icon component format with this PR. Could you do that? Otherwise the changes look good!

2022-02-11 12:07 UTC, georgiee commented on src/components/legacy/icons/social-icons/whatsapp.tsx
> +      fill="currentColor"
that's the right approach. Ideally we would get rid of those legacy icons and use the icon component instead?

2022-02-11 13:05 UTC, milljoniaer commented on src/components/legacy/icons/social-icons/whatsapp.tsx
> +      fill="currentColor"
thank you for your suggestion. Please have another look. I used the Icon Component in both, the share panels and the social links in the navigation

2022-02-22 13:33 UTC, feedm3 approved these changes
Very good, all icons are now in their separate files. Let's merge this 🚀

2022-02-25 08:06 UTC, georgiee requested changes
thanks for moving the icons 💫
Please fix the alignment though by talking to Verena so you could the right assets 🙏

2022-02-25 08:06 UTC, georgiee commented on src/assets/icons/twitter.svg
>      viewBox="0 0 27 22"
a bounding box of `0 0 24 24` is required to properly align. You can't just change the numbers as the underlying vectors don't fit the 1:1 aspect ratio.  I think it's best to ask Verena for help. Usually you create a square of 24x24px in your favourite illustration app and insert and scale the icons so it's properly aligned.

This issue happens in the other icons too.

![Screenshot 2022-02-25 at 09 03 16](https://user-images.githubusercontent.com/1701755/155678201-bf1bda5a-e5ac-4b42-9bca-b1ebe8bc4b37.png)

2022-02-25 09:54 UTC, georgiee approved these changes
icons are updated and it looks properly aligned. thank you, let's merge!

![Screenshot 2022-02-25 at 10 54 25](https://user-images.githubusercontent.com/1701755/155694467-23a17721-e887-4882-a3b5-e26fdf4645f9.png)

2022-02-25 09:54 UTC, georgiee commented on src/assets/icons/email-24.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
looks good 👍

2022-02-25 09:54 UTC, georgiee commented on src/assets/icons/linked-in-24.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
👍

2022-02-25 09:54 UTC, georgiee commented on src/assets/icons/twitter-24.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
👍

2022-02-25 09:57 UTC, merged