[wip]: Meta tags
satellytes/satellytes.com pull request #40
Opened 2020-08-13 09:49 UTC by katerynabugaieva

General: 
![Screenshot 2020-08-13 at 16 06 09](https://user-images.githubusercontent.com/35267034/90144297-f12b8380-dd7e-11ea-89a2-dca4d71a0fef.png)

Facebook:
![Screenshot 2020-08-13 at 17 17 52](https://user-images.githubusercontent.com/35267034/90153270-0d342280-dd89-11ea-8a0b-98af0090bd5e.png)

Twitter
![Screenshot 2020-08-13 at 18 16 55](https://user-images.githubusercontent.com/35267034/90165646-42e10780-dd99-11ea-915f-ab2f281d3e59.png)

LinkedIn 
![Screenshot 2020-09-03 at 13 28 21](https://user-images.githubusercontent.com/35267034/92109535-7b4c9200-ede9-11ea-8851-cf063ba61aef.png)

Xing
![Screenshot 2020-09-03 at 13 28 55](https://user-images.githubusercontent.com/35267034/92109558-856e9080-ede9-11ea-9e2f-7c2d05edd3c1.png)

*TODO*:
Whatsapp:
-add picture in preview
![Screenshot 2020-08-13 at 16 07 54](https://user-images.githubusercontent.com/35267034/90145245-048b1e80-dd80-11ea-9a08-25cb47990c23.png)

2020-09-02 06:07 UTC, feedm3 approved these changes

2020-09-02 06:07 UTC, feedm3 commented on src/components/seo.tsx
>    meta?: [any];
I guess we can remove this property?

2020-09-02 06:07 UTC, feedm3 commented on src/components/seo.tsx
> +  image?: string;
Better call it `imageSrc`, makes it a bit more clear

2020-09-02 06:07 UTC, feedm3 commented on src/templates/blog-post.tsx
> +        image={data.markdownRemark.frontmatter.image}
use the excerp from the markdown as description. you can check the `blog.tsx` for more information

2020-09-02 12:23 UTC, katerynabugaieva commented on src/components/seo.tsx
>    meta?: [any];
was solved with next commits

2020-09-03 08:39 UTC, feedm3 requested changes

2020-09-03 08:39 UTC, feedm3 commented on src/components/seo.tsx
> +      <meta property="og:site_name" content={metaDescription} />
`site_name` should be the `title`. `description` is too long

But still nice that you add the custom description as property, as it's already used on `twitter:desription` for example!

2020-09-03 12:04 UTC, feedm3 approved these changes

2020-09-03 12:27 UTC, merged