feat(AboutUs): add impressions gallery
satellytes/satellytes.com pull request #707
Opened 2023-03-02 09:37 UTC by hofmann-felix

2023-03-03 11:39 UTC, georgiee requested changes
Great approach by reusing the previous implementation in the other draft PR while addressing my concerns I had in there ✨

Content-wise I have one issue with the header missing text, so I hold back this PR until clarified 🙏

2023-03-03 11:39 UTC, georgiee commented on src/components/pages/about-us/impressions.tsx
> +      >
That's missing:
![Screenshot 2023-03-03 at 12 28 33](https://user-images.githubusercontent.com/1701755/222710215-102b1900-2799-4746-bdb8-c426b0bbab8b.png)


In the PR you said that content follows. But I think it's not acceptable to merge content that does not hold any content and instead the translation keys. Can you share your approach in detail?

2023-03-03 11:39 UTC, georgiee commented on src/components/pages/about-us/impressions.tsx
> +  grid-template-rows: repeat(auto-fill, 250px);
So that solves the row count issue I highlighted on the previous draft by @timonsommer  🙌

2023-03-06 07:38 UTC, hofmann-felix commented on src/components/pages/about-us/impressions.tsx
> +      >
@georgiee Currently there is no English version for this yet. Gholam would like to have a stand where he can merge all branches so that he can then insert the text. How do we want to proceed?

2023-03-06 14:06 UTC, georgiee commented on src/components/pages/about-us/impressions.tsx
> +      >
I'm sorry I did not recognize that you merge into a different branch. That's 100% fine then. I though I saw the main branch there when I wrote this comment.

2023-03-06 14:06 UTC, georgiee approved these changes

2023-03-06 14:14 UTC, merged