feat: add new hero style
satellytes/satellytes.com pull request #708
Opened 2023-03-02 14:06 UTC by hofmann-felix

2023-03-02 14:45 UTC, hofmann-felix commented
There is still the `Aurora` component with its corresponding child components. I'm not quite sure if the components should be deleted or if we want to keep those. It would be nice to here some opinions about that. Currently they don't have any usage

2023-03-03 11:45 UTC, georgiee requested changes
The technical changes are looking good. I really don't agree with the decision to introduce that grey in grey hero. It's dull, it's not interesting. I would like to keep the Aurora effect at least on the landingpage. On the other side, you already implementing it is a sign that I'm too late giving that feedback.

What's your opinion on that hero issue?
I would like to hold it back for a short while just to ask the question internally once 🙏

2023-03-03 11:45 UTC, georgiee commented on src/components/content/heroes/heroes.stories.mdx
> -# Aurora Hero
In hindsight we had good ambitions creating storybook content for our website but I doubt folks had using or maintained it properly 😬  Maybe we can remove storybook content entirely over time

2023-03-06 07:41 UTC, hofmann-felix commented
@georgiee I've also talked to Gholam and Dastan about it and we're all not big fans of the new background either. I'll switch the PR to draft until a design decision is made here.

2023-03-06 09:38 UTC, hofmann-felix commented
After the requirements have changed and the background does not change at all, I am closing this PR. For the text/size changes I will create a new PR.

2023-03-06 09:38 UTC, closed without merging