fix: contact page accessibility problems
satellytes/satellytes.com pull request #792
Opened 2024-01-09 16:50 UTC by virus-rpi

### Changes:
- Error message color changed from #FF0D35 to #EB0027 to make the color contrast WCAG AA compliant 
- Changes error messages so that they suggest a fix (e.g. "Your name is missing" to  "The field name is not filled in. Please fill in the field name to send the message.") 
- Made the honypot fields aria-invisible so that they don't get read by screen readers
- Added placeholders in the contact form
- Added a aria-label to the google maps link

2024-01-18 08:14 UTC, georgiee requested changes, later dismissed
Thanks for the good catches! Especially the honeypot thing is embarasing 😬 I've found some issues to fix, thanks!

2024-01-18 08:14 UTC, georgiee commented on src/assets/locales/en/translations.json
> +  "contact.email-placeholder": "e.g. your-email@adress.com",
never ever use actual domains in test-data, dummy data etc because you an always end up sending some mail to that address. There is a domain example.com that is guaranteed never to be owned by anyone. Always use that domain for constructed emails addresses. Here you could use `email@example.com`

2024-01-18 08:14 UTC, georgiee commented on src/components/forms/text-input/text-input.tsx
> +        placeholder={props.placeholder}
can you explain why you add placeholders. Is that read by a screen reader? They are not adding much here because forms are pretty common and if I use a screen reader to fill out a form I probably now what to provide if the input is named "email" and such. Maybe we can remove it if there is not a deeper thought involved?

2024-01-18 08:14 UTC, georgiee commented on src/components/layout/theme.tsx
> +      errorMessage: '#EB0027',
👍

2024-01-18 08:14 UTC, georgiee commented on src/components/pages/contact/address.tsx
> +        aria-label={'Open Satellytes Google Maps profile in a new tab'}
I can see it with the VO rotor. Much better. The "open" is kind of weird because any link is kind of "to be opened" anyway? But I have no better proposal 

![CleanShot 2024-01-16 at 17 53 45](https://github.com/satellytes/satellytes.com/assets/1701755/987ada9d-48fa-44f6-a697-3be98a8084b0)
![CleanShot 2024-01-16 at 17 54 26](https://github.com/satellytes/satellytes.com/assets/1701755/9a85e38d-ccd5-4ec1-a8f6-a30bda447598)

2024-01-18 08:14 UTC, georgiee commented on src/components/pages/contact/honeypot.tsx
> +          aria-hidden={true}
I think that aria hidden is not required at all.

> Adding aria-hidden="true" to an element removes that element and all of its children from the accessibility tree. 

via https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden

2024-01-18 08:14 UTC, georgiee commented on src/components/pages/contact/honeypot.tsx
> +  aria-hidden: true;
That is wrong. aria hidden is not a valid css statement. Not needed as you apply aria hidden on the label already

2024-01-18 08:14 UTC, georgiee commented on src/templates/blog-post.tsx
> +  }
please replace with a more idiomatic fix: 

```suggestion
  const  shareImagePath = heroImage.shareImage?.resize.src;
```

2024-01-22 16:29 UTC, virus-rpi commented on src/components/forms/text-input/text-input.tsx
> +        placeholder={props.placeholder}
They are read by screen readers. But you're right they are a bit redundant to the labels. Should I remove them?

2024-01-29 13:50 UTC, maxmarkus commented on src/components/forms/text-input/text-input.tsx
> +        placeholder={props.placeholder}
I just tried it with and without placeholders and VoiceOver and it feels a bit better without. Its a hell lot of fast read text in between what it reads out as similar to "name, textfield, main" and "you are in a text field, by typing you enter text into that field". 
So I would vote for removing the place holders.

2024-01-29 13:55 UTC, maxmarkus commented
Idea: How about setting the whole map as aria-hidden? For visually impaired people it seems to bring no benefits, it has 5-6 links that can be tabbed and the readout is weird (screenshot below). Since we have the google maps link below, that might be enough.
 
<img width="699" alt="screenshot of open streetmap zoom-in voice-over" src="https://github.com/satellytes/satellytes.com/assets/1720843/a7c7b5d9-6007-499b-94e4-6338e30d656f">

2024-01-29 15:49 UTC, virus-rpi commented
> Idea: How about setting the whole map as aria-hidden? For visually impaired people it seems to bring no benefits, it has 5-6 links that can be tabbed and the readout is weird (screenshot below). Since we have the google maps link below, that might be enough.
> 
> <img alt="screenshot of open streetmap zoom-in voice-over" width="699" src="https://private-user-images.githubusercontent.com/1720843/300484320-a7c7b5d9-6007-499b-94e4-6338e30d656f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDE0ODIsIm5iZiI6MTcwNjU0MTE4MiwicGF0aCI6Ii8xNzIwODQzLzMwMDQ4NDMyMC1hN2M3YjVkOS02MDA3LTQ5OWItOTRlNC02MzM4ZTMwZDY1NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTUxMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA2YjA2MmE0OTZjMjU5NmFhYzc4YWQ3ZjY4ZDAzNjA4ZGIxYmI2NWI0MzAyNjc4NDRiZDkxYzA2YjcxZDk0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TcfejU-fuC0Ss7PywgChJ6uODfGoWNHWMRoWKwUwviU">
> Edit: After writing this, I realized that [leafletjs is accessible](https://leafletjs.com/examples/accessibility/). But the idea can still be valid.

i tried aria hiding the map but VoiceOver still reads it despite the aria-hidden=true.

2024-02-05 16:03 UTC, virus-rpi commented
> > Idea: How about setting the whole map as aria-hidden? For visually impaired people it seems to bring no benefits, it has 5-6 links that can be tabbed and the readout is weird (screenshot below). Since we have the google maps link below, that might be enough.
> > <img alt="screenshot of open streetmap zoom-in voice-over" width="699" src="https://private-user-images.githubusercontent.com/1720843/300484320-a7c7b5d9-6007-499b-94e4-6338e30d656f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDE0ODIsIm5iZiI6MTcwNjU0MTE4MiwicGF0aCI6Ii8xNzIwODQzLzMwMDQ4NDMyMC1hN2M3YjVkOS02MDA3LTQ5OWItOTRlNC02MzM4ZTMwZDY1NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTUxMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA2YjA2MmE0OTZjMjU5NmFhYzc4YWQ3ZjY4ZDAzNjA4ZGIxYmI2NWI0MzAyNjc4NDRiZDkxYzA2YjcxZDk0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TcfejU-fuC0Ss7PywgChJ6uODfGoWNHWMRoWKwUwviU">
> > Edit: After writing this, I realized that [leafletjs is accessible](https://leafletjs.com/examples/accessibility/). But the idea can still be valid.
> 
> i tried aria hiding the map but VoiceOver still reads it despite the aria-hidden=true.

should i keep looking for a way to make the map aria-hidden or should i just leave it as it is, since leaflet is accessible

2024-02-05 16:39 UTC, virus-rpi commented
I found a way to make the map aria-hidden but it is still tab focusable and i could not figure out how to remove it from the tab order (`tabIndex = {-1}` gets ignored)

2024-02-06 09:16 UTC, maxmarkus approved these changes
Despite the fact that the general description "see no evil monkey emoji, because it's embarrassing" feels a bit weird I am approving it. We might think about rewording anyway.

2024-02-06 15:20 UTC, merged