feat: add cookie consent v3
satellytes/satellytes.com pull request #825
Opened 2024-10-08 09:07 UTC by ipeke94

Based on the conversation with Georgios, I added Cookie Consent script from here -> https://github.com/orestbida/cookieconsent?tab=readme-ov-file 

Note: We can add German translation version.

Kindly checkout the gif below:

![cookie-consent-trial-1234](https://github.com/user-attachments/assets/2374b3b1-ce81-4c23-9b22-117e7ace7b6f)

2024-10-08 09:26 UTC, ipeke94 commented on src/components/CookieConsent.tsx
> +    document.cookie = `_li_id=some_value; max-age=${twoYears}; path=/`;
We can add more meaningful values: https://help.leadinfo.com/en/add-leadinfo-to-your-cookie-banner-solution

2024-10-08 10:54 UTC, georgiee requested changes
Hi thanks for the start,
I've provided some feedback regarding the integration.

2024-10-08 10:54 UTC, georgiee commented on package.json
> +    "vanilla-cookieconsent": "3.0.1",
👍

2024-10-08 10:54 UTC, georgiee commented on src/@types/cookieconsent.d.ts
Why manually, we have the `types` project (https://github.com/DefinitelyTyped/DefinitelyTyped)

I think those should be enough:
https://www.npmjs.com/package/@types/cookieconsent

2024-10-08 10:54 UTC, georgiee commented on src/components/CookieConsent.tsx
> +        },
we don't need that category, do we ? Seems like you copied that as seen in the docs?

2024-10-08 10:54 UTC, georgiee commented on src/components/CookieConsent.tsx
> +            },
1. Is there no default language shipped?
2. Put them into a separate en file, I think that's manageable and makes it less noisy to work with the config.

2024-10-08 10:54 UTC, georgiee commented on src/components/CookieConsent.tsx
> +    document.cookie = `_li_id=some_value; max-age=${twoYears}; path=/`;
The article explains the nature of the cookies involved. I don't think that we're supposed to set those cookies.
Instead you have to pull in the matching script through the scripts management of the cookie consent js I think ?

https://cookieconsent.orestbida.com/advanced/manage-scripts.html

I'm not sure how to distinguish the two different modes (with cookies and without). Maybe there are two different scripts possible or so?

--> If that's not a given use case to allow both scenarios (cookie and without cookies) then let's enable cookies in the backend and integrate the tracker only when the consent was given. Maybe we find a solution afterwards.

2024-10-08 10:54 UTC, georgiee commented on src/components/layout/leadinfo-script.tsx
> +  const [script, setScript] = useState<HTMLScriptElement | null>(null);
as said I think it's easier to use the script manager instead of manually bootstrapping it

2024-10-15 13:19 UTC, ipeke94 commented on src/components/layout/leadinfo-script.tsx
> +    leadinfoScript.setAttribute('data-category', 'analytics');
In the leadInfo side, the cookies are already enabled.

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/6efa7ea0-3253-443d-86cc-69ce22b63803">

As far as I see in the [documentation](https://cookieconsent.orestbida.com/advanced/manage-scripts.html) when we add these two attributes, that prevents script execution until consent is given.

Cookies are enabled:


<img width="1152" alt="image" src="https://github.com/user-attachments/assets/d70c5209-4fbf-4f87-8294-e7c035dcd541">
<img width="710" alt="Screenshot 2024-10-15 at 3 13 10 PM" src="https://github.com/user-attachments/assets/581108fa-955e-4c07-84e4-8d7bee473504">
<img width="984" alt="Screenshot 2024-10-15 at 3 18 28 PM" src="https://github.com/user-attachments/assets/e260a00a-4a6e-4106-817b-ca25d9d77007">


----


Cookies aren't enabled:
 

<img width="738" alt="Screenshot 2024-10-15 at 3 11 41 PM" src="https://github.com/user-attachments/assets/d3585fdb-daa3-4748-b824-424db92decb2">
<img width="733" alt="Screenshot 2024-10-15 at 3 11 48 PM" src="https://github.com/user-attachments/assets/d3dab706-c022-4fdd-9ae6-129c6ed4dba4">

2024-10-16 21:11 UTC, ipeke94 commented on src/components/layout/leadinfo-script.tsx
> +  const [script, setScript] = useState<HTMLScriptElement | null>(null);
Hello, 

Thank you for the feedback and your time🙏. I tried to block/manage script tags according to the [document](https://cookieconsent.orestbida.com/advanced/manage-scripts.html) you sent. You can see some FAQs in my comment below. Accordingly, when we do this, different cookies are set when analytics data is accepted by Leadinfo. The cookies are listed below possibly related to  [li_id and li_ses cookies](https://help.leadinfo.com/en/add-leadinfo-to-your-cookie-banner-solution) in terms of tracking user sessions and identifying visitors. (like Google Analytics(_ga cookies) or HubSpot (__hstc, hubspotutk) or _hssrc session cookie)

<img width="1323" alt="Screenshot 2024-10-16 at 10 43 00 PM" src="https://github.com/user-attachments/assets/d1c25227-98df-4193-b8db-4e0b742e3917">

Do you think we need to add detailed descriptions of these cookies under analytics or the relevant section?

2026-03-30 13:28 UTC, closed without merging